# Site settings
title: clement Hamon
email: clementhamon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here you will find couple of things that went to my mind, things I wanted to learn, experiment and share.
  If anyone can benefit from it, I would be more than happy ;).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://clement-hamon.github.io" # the base hostname & protocol for your site
github_username:  clement-hamon

# Build settings
markdown: kramdown
